on:
    workflow_dispatch:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

name: Validate and publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run validate
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
          retention-days: 1
      - name: rename docs/README.md to index.qmd
        task: CmdLine@2
        inputs: rename docs/README.md docs/index.qmd
      - name: copy doscs/index.qmd to root
        task: CopyFiles@2 
        inputs:
          SourceFolder: docs
          TargetFolder: 
      - name : Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Deploy to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
